[package]
name = "houjing"
version = "0.1.0"
edition = "2021"

[dependencies]
tagger = "4.3.3"
slotmap = "1.0.2"
rug = "1.15.0"
# num = "0.4"
z3 = {version="0.11.2", features = ["static-link-z3"]}
# log = "0.4"
# lazy_static = "1"
# env_logger = "0.6"
# semver = "0.9"
